-- AlterTable
ALTER TABLE `Utilisateur` MODIFY `numero` VARCHAR(191) NULL,
    MODIFY `dateNaissance` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `pays` VARCHAR(191) NULL,
    MODIFY `ville` VARCHAR(191) NULL,
    MODIFY `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updatedAt` DATETIME(3) NULL;
